export default function Original_Containers() {
  return [
    {
      id: 1,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 2,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 3,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 4,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 5,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 6,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 7,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 8,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 9,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },

    {
      id: 10,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 11,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 12,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 13,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 14,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 15,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 16,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 17,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 18,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 19,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },

    {
      id: 20,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 21,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 22,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 23,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 24,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 25,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 26,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 27,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 28,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 29,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 30,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 31,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 32,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 33,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 34,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 35,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },

    {
      id: 36,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 37,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 38,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 39,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 40,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 41,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
    {
      id: 42,
      plant_id: null,
      plant_pic: null,
      occupied: false,
    },
  ];
}
